[package]
name = "ascii-pay-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

axum = { version="0.6.4" }
tokio = { version = "1.25.0", features = ["full"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "any", "postgres"] }

dotenv = "0.15.0"
log = "0.4.17"
env_logger = "0.10.0"
