[package]
name = "ascii-pay-server"
version = "0.1.0"
authors = ["Lars Westermann <lars-westermann@live.de>", "Felix Wittwer <dev@felixwittwer.de>"]
description = "[WIP] A prepaid system."
edition = "2018"
build = "build.rs"

[dependencies]
# data storage
time = "0.2"
chrono = {version = "0.4", features = ["serde"]}
diesel = {version = "1.4", features = ["postgres", "uuidv07", "r2d2", "chrono"]}
diesel_migrations = "1.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = {version = "0.8", features = ["serde", "v4"]}
bb8 = "0.7"
bb8-postgres = "0.7"
bb8-redis = "0.10"

# security
openssl = "0.10"
argon2rs = "0.2"
rand_core = "0.6"
rand = "0.8"
aes = "0.7"
hex-literal = "0.3"
block-modes = "0.8"
byteorder = "1.4"
des = "0.7"

# web server
actix-web = {version = "4.0.0-beta.12", features = ["openssl"]}
actix-rt = "2.3"
actix-http = "3.0.0-beta.13"
actix-files = "0.6.0-beta.9"
actix-cors = "0.6.0-beta.4"
awc = {version = "3.0.0-beta.11", features = ["openssl"]}
http = "0.2"

# graphql
async-graphql = {version = "3.0.7", features = ["uuid", "chrono"]}
async-graphql-actix-web = "3.0.7"
async-stream = "0.3"
async-std = "1.10"

# apple wallet pass
wallet-pass = "0.2"

# utils
derive_more = "0.99"
dotenv = "0.15"
log = "0.4"
env_logger = "0.9"
futures = "0.3"
futures-util = "0.3"
async-trait = "0.1.51"
lazy_static = "1.4"
clap = "2.33"
sublime_fuzzy = "0.6"
base64 = "0.13"
generic-array = "0.14"
tokio = { version = "1.14", features=["full"] }
threadpool = "1.8"
grpcio = "0.9"
protobuf = "2.25"

# sending mails
lettre = "0.9"
lettre_email = "0.9"

[build-dependencies]
protoc-grpcio = "3.0"
