[package]
name = 'ascii-prepaid-system'
version = '0.1.0'
authors = ['Lars Westermann <lars-westermann@live.de>', 'Felix Wittwer <dev@felixwittwer.de>']
edition = '2018'
build = "build.rs"

[dependencies]
actix-identity = '0.1.0'
actix-web = '1.0.3'
argonautica = '0.2.0'
chrono = {version = '0.4.6', features = ['serde']}
derive_more = '0.15.0'
diesel = {version = '1.4.2', features = ['sqlite','uuidv07', 'r2d2', 'chrono']}
dotenv = '0.14.1'
env_logger = '0.6'
futures = '0.1'
r2d2 = '0.8'
lazy_static = '1.3.0'
serde = '1.0'
serde_derive = '1.0'
serde_json = '1.0'
uuid = {version = '0.7', features = ['serde', 'v4']}

[build-dependencies]
sass-rs = "0.2.2"