[package]
name = "ascii-pay-server"
version = "0.1.0"
authors = ["Lars Westermann <lars-westermann@live.de>", "Felix Wittwer <dev@felixwittwer.de>"]
description = "[WIP] A prepaid system."
edition = "2018"
build = "build.rs"

[dependencies]
actix-identity = "0.3"
actix-web = {version = "3.3", features = ["openssl"]}
actix-files = "0.5"
actix-multipart = "0.3"
actix-rt = "2.2"
actix-http = "2.2"
handlebars = {version = "3.5", features = ["dir_source"]}
argonautica = "0.2"
time = "0.2"
chrono = {version = "0.4", features = ["serde"]}
derive_more = "0.99"
diesel = {version = "1.4", features = ["postgres", "uuidv07", "r2d2", "chrono"]}
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
r2d2 = "0.8"
lazy_static = "1.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = {version = "0.8", features = ["serde", "v4"]}
clap = "2.33"
sublime_fuzzy = "0.6"
base64 = "0.13"
rand_core = "0.6"
rand = "0.8"
aes = "0.7"
generic-array = "0.14"
byteorder = "1.4"
hex-literal = "0.3"
block-modes = "0.8"
rpassword = "5.0" 
wallet-pass = "0.2"
a2 = "0.6"
tokio = "1.9"
openssl = "0.10"

# for sending mails
lettre = "0.9"
lettre_email = "0.9"

[build-dependencies]
sass-rs = "0.2"
