[package]
name = "ascii-pay-server"
version = "0.1.0"
authors = ["Lars Westermann <lars-westermann@live.de>", "Felix Wittwer <dev@felixwittwer.de>"]
description = "[WIP] A prepaid system."
edition = "2018"
build = "build.rs"

[dependencies]
# data storage
time = "0.3"
chrono = {version = "0.4", features = ["serde"]}
diesel = {version = "2.0", features = ["r2d2", "postgres", "extras", "i-implement-a-third-party-backend-and-opt-into-breaking-changes"]}
diesel_migrations = "2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = {version = "1.1", features = ["serde", "v4"]}
bb8 = "0.8"
#bb8-postgres = "0.8"
bb8-redis = "0.12"

# security
openssl = "0.10"
argon2rs = "0.2"
rand_core = "0.6"
rand = "0.8"
hex-literal = "0.3"
#byteorder = "1.4"
block-modes = "0.8"
aes = "0.7"
des = "0.7"

# web server
actix-web = {version = "4.2", features = ["openssl"]}
actix-rt = "2.7"
actix-http = "3.2"
actix-files = "0.6"
actix-cors = "0.6"
awc = {version = "3.0", features = ["openssl"]}
http = "0.2"

# graphql
async-graphql = {version = "4.0", features = ["uuid", "chrono"]}
async-graphql-actix-web = "4.0"
#async-stream = "0.3"
#async-std = "1.10"

# apple wallet pass
wallet-pass = "0.3"

# utils
derive_more = "0.99"
dotenv = "0.15"
log = "0.4"
env_logger = "0.9"
futures = "0.3"
futures-util = "0.3"
async-trait = "0.1.51"
lazy_static = "1.4"
clap = { version = "3.2", features = ["cargo"] }
sublime_fuzzy = "0.6"
base64 = "0.13"
generic-array = "0.14"
tokio = { version = "1.14", features=[ "full", "rt-multi-thread" ] }
#threadpool = "1.8"
grpcio = { version = "0.12", default-features = false, features=["prost-codec", "openssl"] }
#bytes = "1.2"
prost = "0.11"
git2 = "0.15"

# sending mails
#lettre = "0.10"
lettre_email = "0.9"

[build-dependencies]
grpcio-compiler = { version = "0.12", default-features = false, features=["prost-codec"] }
