[package]
name = "ascii-pay-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

axum = { version="0.6.4", features=["multipart"] }
tower-http = { version = "0.3", features = ["limit","cors","compression-br"] }
tokio = { version = "1.25.0", features = ["full"] }
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "any", "postgres"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version="1.0.91" }
argon2rs = { version="0.2.5", default-features = false }
base64 = { version="0.21.0" }
aide = { version="0.10.0", features=["redoc", "axum", "axum-extra", "macros", "axum-multipart"] }
schemars = { version = "0.8.11" }

dotenv = "0.15.0"
log = "0.4.17"
env_logger = "0.10.0"
