[package]
name = "ascii-prepaid-system"
version = "0.1.0"
authors = ["Lars Westermann <lars-westermann@live.de>"]
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-rt = "0.2.3"
actix-web = "1.0.3"
actix-files = "0.1.3"
actix-identity= "0.1.0"

bcrypt = "0.4.0"
chrono = { version = "0.4.7", features = ["serde"] }
diesel = { version = "1.4.2", features = ["sqlite", "uuid", "r2d2", "chrono"] }
dotenv = "0.14.1"
derive_more = "0.15.0"
env_logger = "0.6.1"
jsonwebtoken = "6.0.1"
futures = "0.1.28"
r2d2 = "0.8.5"
serde_derive = "1.0.94"
serde_json = "1.0.39"
serde = "1.0.94"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
rpassword = "3.0.2"
