version: "3"
services:
  db:
    image: "postgres"
    container_name: "ascii-prepaid-system-postgres"
    environment:
      - POSTGRES_USER=ascii
      - POSTGRES_PASSWORD=ascii
      - POSTGRES_DB=ascii-prepaid-system
    ports:
      - "54320:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data