version: "3"
services:
  db:
    build:
      dockerfile: ./docker/Dockerfile.db
      context: .
    container_name: "ascii-pay-postgres"
    environment:
      - POSTGRES_USER=ascii
      - POSTGRES_PASSWORD=ascii
      - POSTGRES_DB=ascii-pay
    ports:
      - "54320:5432"
    volumes:
      - ./dist/postgres:/var/lib/postgresql/data
