# configuration shared between dev and release
version: "3"
services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    image: asciipay/server:latest
    restart: always
    container_name: "ascii-pay-server"
    environment:
      - HOST=0.0.0.0
      - HTTP_PORT=8080
      - GRPC_PORT=8081
      - DATABASE_URI=postgres://ascii:ascii@postgres:5432/ascii-pay
      - REDIS_URI=redis://redis:6379/1
      - PRODUCT_STORAGE=./ascii-pay-products/main.json
      - MAIL_SENDER=payments@ascii.coffee
      - MAIL_SENDER_NAME=Ascii Pay Service
      - MAIL_URL=mail.example.local
      - MAIL_USER=username
      - MAIL_PASSWORD=password
      - CRON_SECRET=12345678
      - BASE_URL=https://ascii.pixix4.com/
      - API_ACCESS_KEY=true
    volumes:
      - ./ascii-pay-products:/opt/ascii-pay-server/ascii-pay-products
      - ./certificates:/opt/ascii-pay-server/certificates
      - ./AsciiPayCard.pass:/opt/ascii-pay-server/AsciiPayCard.pass
    depends_on:
      - postgres
      - redis
    networks:
      - default

  postgres:
    image: postgres:13-alpine
    container_name: "ascii-pay-postgres"
    restart: always
    environment:
      - POSTGRES_USER=ascii
      - POSTGRES_PASSWORD=ascii
      - POSTGRES_DB=ascii-pay
    ports:
      - "5432:5432"
    volumes:
      - ./dist/postgres:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis:6-alpine
    container_name: "ascii-pay-redis"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./dist/redis:/var/lib/redis
    networks:
      - default

  proxy:
    image: nginx:1.21-alpine
    container_name: "ascii-pay-proxy"
    restart: "always"
    volumes:
      - ./test-certificates:/etc/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    ports:
      - 443:443
    networks:
      - default
