# configuration shared between dev and release
version: "3"
services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: "ascii-pay-server-dist"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DATABASE_URL=postgres://ascii:ascii@postgres:5432/ascii-pay
      - REDIS_URL=redis://redis:6379/1
      - MAIL_SENDER=payments@ascii.coffee
      - MAIL_SENDER_NAME=Ascii Pay Service
      - MAIL_URL=mail.example.local
      - MAIL_USER=username
      - MAIL_PASSWORD=password
      - CRON_SECRET=12345678
      - IMAGE_PATH=./img
      - BASE_URL=https://ascii.pixix4.com/
      - API_ACCESS_KEY=
    expose:
      - "8080"
      - "50051"
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - ./dist/img:/opt/ascii-pay-server/img
      - ./certificates:/opt/ascii-pay-server/certificates
      - ./AsciiPayCard.pass:/opt/ascii-pay-server/AsciiPayCard.pass
    depends_on:
      - postgres
      - redis
    networks:
      - default
    restart: always
  postgres:
    image: postgres:13-alpine
    container_name: "ascii-pay-postgres-dist"
    environment:
      - POSTGRES_USER=ascii
      - POSTGRES_PASSWORD=ascii
      - POSTGRES_DB=ascii-pay
    ports:
      - "5432:5432"
    volumes:
      - ./dist/postgres:/var/lib/postgresql/data
    networks:
      - default
    restart: always
  redis:
    image: redis:6-alpine
    container_name: "ascii-pay-redis-dist"
    ports:
      - "6379:6379"
    volumes:
      - ./dist/redis:/var/lib/redis
    networks:
      - default
    restart: always
