# configuration shared between dev and release
version: "3"
services:
  web:
    build: .
    container_name: "ascii-pay-server-dist"
    environment:
      - HOST=0.0.0.0
      - DATABASE_URL=postgres://ascii:ascii@db:5432/ascii-pay
      - MAIL_SENDER=payments@ascii.coffee
      - MAIL_SENDER_NAME="Ascii Pay Service"
      - MAIL_URL=mail.example.local
      - MAIL_USER=username
      - MAIL_PASSWORD=password
      - CRON_SECRET=12345678
      - IMAGE_PATH="./img/"
    ports:
      - "8080:8080"
    volumes:
      - ./dist/img:/opt/ascii-pay-server/img
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: docker/Dockerfile.db
    container_name: "ascii-pay-postgres-dist"
    environment:
      - POSTGRES_USER=ascii
      - POSTGRES_PASSWORD=ascii
      - POSTGRES_DB=ascii-pay
    volumes:
      - ./dist/postgres:/var/lib/postgresql/data
