version: "3"
services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    image: asciipay/server:latest
    restart: always
    container_name: "ascii-pay-server"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=3000
      - DATABASE_URL=postgres://ascii:ascii@postgres:5432/ascii-pay
      - RUST_LOG=info,sqlx::query=warn
      - DOMAIN_NAME=http://localhost:8080
    depends_on:
      - postgres
    volumes:
      - ./AsciiPayCard.pass:/opt/ascii-pay-server/AsciiPayCard.pass
      - ./certificates:/opt/certificates
    ports:
      - "3000:3000"
    networks:
      - default
  postgres:
    image: postgres:13-alpine
    container_name: "ascii-pay-postgres"
    restart: always
    environment:
      - POSTGRES_USER=ascii
      - POSTGRES_PASSWORD=ascii
      - POSTGRES_DB=ascii-pay
    ports:
      - "5432:5432"
    volumes:
      - ./dist/postgres:/var/lib/postgresql/data
    networks:
      - default
