# configuration shared between dev and release
version: "3"
services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: "ascii-pay-server-dist"
    environment:
      - HOST=0.0.0.0
      - HTTP_PORT=8080
      - GRPC_PORT=8081
      - DATABASE_URI=postgres://ascii:ascii@postgres:5432/ascii-pay
      - REDIS_URI=redis://redis:6379/1
      - PRODUCT_STORAGE=./ascii-pay-products/main.json
      - MAIL_SENDER=payments@ascii.coffee
      - MAIL_SENDER_NAME=Ascii Pay Service
      - MAIL_URL=mail.example.local
      - MAIL_USER=username
      - MAIL_PASSWORD=password
      - CRON_SECRET=12345678
      - BASE_URL=https://ascii.pixix4.com/
      - API_ACCESS_KEY=
    expose:
      - "8080"
      - "50051"
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./ascii-pay-products:/opt/ascii-pay-server/ascii-pay-products
      - ./certificates:/opt/ascii-pay-server/certificates
      - ./AsciiPayCard.pass:/opt/ascii-pay-server/AsciiPayCard.pass
    depends_on:
      - postgres
      - redis
    networks:
      - default
    restart: always
  postgres:
    image: postgres:13-alpine
    container_name: "ascii-pay-postgres-dist"
    environment:
      - POSTGRES_USER=ascii
      - POSTGRES_PASSWORD=ascii
      - POSTGRES_DB=ascii-pay
    ports:
      - "5432:5432"
    volumes:
      - ./dist/postgres:/var/lib/postgresql/data
    networks:
      - default
    restart: always
  redis:
    image: redis:6-alpine
    container_name: "ascii-pay-redis-dist"
    ports:
      - "6379:6379"
    volumes:
      - ./dist/redis:/var/lib/redis
    networks:
      - default
    restart: always
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   ports:
  #     - "5050:80"
