@startuml

title NFC Flow

Card <- Proxy: Request identification
Card -> Proxy: Respond(atr)

Proxy -> Proxy: Select card handler

Card <- Proxy: Request card id
Card -> Proxy: Respond(id)

group Authentication

Proxy -> Server: Request authentication(id)

else NotFound
Proxy <- Server: Respond NotFound

else Account 
Proxy <- Server: Respond Account(Account)

else AuthenticationNeeded
Proxy <- Server: Respond AuthenticationNeeded(key, challenge)
Card <- Proxy: Request Secret(key)
Card -> Proxy: Respond(Secret)

Proxy -> Proxy: Calculate challange-reponse
Proxy -> Server: Request authentication(id, challange-reponse)
Proxy <- Server: Respond Account(Account)

else WriteKey
Proxy <- Server: Respond WriteKey(key, secret)
Card <- Proxy: Store Secret(key, secret)
Card -> Proxy: Respond Ok

Proxy -> Server: Request authentication(id)
Proxy <- Server: Respond AuthenticationNeeded(key, challenge)
Card <- Proxy: Request Secret(key)
Card -> Proxy: Respond(Secret)

Proxy -> Proxy: Calculate challange-reponse
Proxy -> Server: Request authentication(id, challange-reponse)
Proxy <- Server: Respond Account(Account)

end

group Payment

Proxy -> Server: Request payment token(id, amount)

else Authorized
Proxy <- Server: Respond Authorized(token)

else AuthenticationNeeded
Proxy <- Server: Respond AuthenticationNeeded(key, challenge)
Card <- Proxy: Request Secret(key)
Card -> Proxy: Respond(Secret)

Proxy -> Proxy: Calculate Challenge Response
Proxy -> Server: Request payment token(id, challange-reponse, amount)
Proxy <- Server: Respond Authorized(token)

end

@enduml
