name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt-get install libpq-dev protobuf-compiler libprotobuf-dev

    - name: Install Rust stable
      run: |
        rustup toolchain update --no-self-update stable
        rustup default stable

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
